version: '3.5'

services:
  # -------------------------------------------------------
  api:
    image: biowonks/mist-api:5252539
    depends_on:
      - pg_db
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgres://mist-admin:mist-admin-password@pg-db:5432/mist
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure


  # -------------------------------------------------------
  pg-db:
    image: biowonks/mist-pg-db:5252539
    volumes:
      - db-10.3:/var/lib/postgresql/data
    environment:
      # The POSTGRES_* variables are passed to the postgresql image
      - POSTGRES_USER
      - POSTGRES_PASSWORD=postgres-passwod

      # These are used by postgres-setup.sh (which uses defaults if not specified)
      - CERT_SUBJ
      - DB_NAME=mist
      - DB_ADMIN_USER=mist-admin
      - DB_ADMIN_PASSWORD=mist-admin-password
      - DB_API_USER=mist-api
      - DB_API_PASSWORD=mist-api-password

      # To customize the postgresql configuration, pass any settings via the PG_CONF variable
      - PG_CONF
    deploy:
      replicas: 1


# -------------------------------------------------------
volumes:
  db-10.3:
